#!/usr/bin/env python3
"""Emit library-specific config files from a shared FCS profile.

Current target support:
- nss: emits NSS_JA4_CONFIG key=value format for the slim NSS hook.

Design note:
Adapters are intentionally separated so additional targets (openssl,
boringssl, nginx module runtime) can be added without changing profile parsing.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
from datetime import datetime, timezone
from typing import Any


def _die(message: str) -> None:
    raise SystemExit(f"error: {message}")


def _load_profile(path: pathlib.Path) -> dict[str, Any]:
    if not path.exists():
        _die(f"input file not found: {path}")

    text = path.read_text(encoding="utf-8")

    if path.suffix.lower() == ".json":
        data = json.loads(text)
    else:
        try:
            import yaml  # type: ignore
        except ModuleNotFoundError:
            _die(
                "YAML input requires pyyaml (pip install pyyaml) or use JSON input"
            )
        data = yaml.safe_load(text)

    if not isinstance(data, dict):
        _die("top-level profile must be an object/map")

    return data


def _nested(obj: dict[str, Any], *keys: str) -> Any:
    cur: Any = obj
    for key in keys:
        if not isinstance(cur, dict):
            return None
        cur = cur.get(key)
    return cur


def _bool_to_int_str(value: Any) -> str | None:
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, int):
        return "1" if value != 0 else "0"
    if isinstance(value, str):
        s = value.strip().lower()
        if s in {"1", "true", "on", "yes"}:
            return "1"
        if s in {"0", "false", "off", "no"}:
            return "0"
    return None


def _csv_int(values: Any) -> str | None:
    if not isinstance(values, list):
        return None

    out: list[str] = []
    for item in values:
        if isinstance(item, int):
            out.append(str(item))
            continue
        if isinstance(item, str):
            s = item.strip()
            try:
                parsed = int(s, 0)
            except ValueError:
                return None
            out.append(str(parsed))
            continue
        return None

    return ",".join(out)


def _csv_tokens(values: Any) -> str | None:
    if not isinstance(values, list):
        return None

    out: list[str] = []
    for item in values:
        if not isinstance(item, str):
            return None
        token = item.strip()
        if not token:
            return None
        if "," in token:
            _die("ALPN tokens must not contain commas")
        out.append(token)

    return ",".join(out)


def _tls_version(value: Any) -> str | None:
    if value is None:
        return None
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        s = value.strip()
        if s:
            return s
    return None


def emit_nss(profile: dict[str, Any]) -> str:
    tls = _nested(profile, "inputs", "tls_client_hello")
    if not isinstance(tls, dict):
        tls = {}

    exec_nss = _nested(profile, "execution", "nss")
    if not isinstance(exec_nss, dict):
        exec_nss = {}

    lines: list[str] = []
    lines.append("# generated by scripts/fcs_emit.py")
    lines.append(f"# utc={datetime.now(timezone.utc).isoformat()}")
    profile_id = profile.get("profile_id")
    if isinstance(profile_id, str) and profile_id.strip():
        lines.append(f"# profile_id={profile_id.strip()}")

    min_v = _tls_version(tls.get("tls_min_version"))
    max_v = _tls_version(tls.get("tls_max_version"))
    if min_v is not None:
        lines.append(f"tls_min={min_v}")
    if max_v is not None:
        lines.append(f"tls_max={max_v}")

    cipher_csv = _csv_int(tls.get("cipher_suites"))
    if cipher_csv is not None:
        lines.append(f"cipher_suites={cipher_csv}")

    cipher_mode = tls.get("cipher_mode")
    if isinstance(cipher_mode, str) and cipher_mode.strip():
        lines.append(f"cipher_mode={cipher_mode.strip()}")

    alpn_csv = _csv_tokens(tls.get("alpn_protocols"))
    if alpn_csv is not None:
        lines.append(f"alpn={alpn_csv}")

    grease = _bool_to_int_str(exec_nss.get("enable_grease"))
    if grease is not None:
        lines.append(f"enable_grease={grease}")

    ch_perm = _bool_to_int_str(exec_nss.get("enable_ch_xtn_permutation"))
    if ch_perm is not None:
        lines.append(f"enable_ch_xtn_permutation={ch_perm}")

    ext_csv = _csv_int(tls.get("extensions"))
    if ext_csv is not None:
        lines.append(f"extension_order={ext_csv}")

    extension_mode = tls.get("extension_mode")
    if isinstance(extension_mode, str) and extension_mode.strip():
        lines.append(f"extension_mode={extension_mode.strip()}")

    sigalg_csv = _csv_int(tls.get("signature_algorithms"))
    if sigalg_csv is not None:
        lines.append(f"signature_algorithms={sigalg_csv}")

    supported_versions_csv = _csv_int(tls.get("supported_versions"))
    if supported_versions_csv is not None:
        lines.append(f"supported_versions={supported_versions_csv}")

    supported_groups_csv = _csv_int(tls.get("supported_groups"))
    if supported_groups_csv is not None:
        lines.append(f"supported_groups={supported_groups_csv}")

    key_share_groups_csv = _csv_int(tls.get("key_share_groups"))
    if key_share_groups_csv is not None:
        lines.append(f"key_share_groups={key_share_groups_csv}")

    psk_modes_csv = _csv_int(tls.get("psk_key_exchange_modes"))
    if psk_modes_csv is not None:
        lines.append(f"psk_key_exchange_modes={psk_modes_csv}")

    sni_mode = tls.get("sni_mode")
    if isinstance(sni_mode, str) and sni_mode.strip():
        lines.append(f"sni_mode={sni_mode.strip()}")

    unsupported: list[str] = []
    for key in [
        "supported_groups",
        "supported_versions",
        "psk_key_exchange_modes",
        "key_share_groups",
    ]:
        if key in tls:
            unsupported.append(key)

    if unsupported:
        lines.append("")
        lines.append("# unsupported by nss-slim hook (kept in FCS, not emitted):")
        for key in unsupported:
            lines.append(f"# - {key}")

    return "\n".join(lines) + "\n"


def emit_openssl(profile: dict[str, Any]) -> str:
    tls = _nested(profile, "inputs", "tls_client_hello")
    if not isinstance(tls, dict):
        tls = {}

    exec_ossl = _nested(profile, "execution", "openssl")
    if not isinstance(exec_ossl, dict):
        exec_ossl = {}

    lines: list[str] = []
    lines.append("# generated by scripts/fcs_emit.py")
    lines.append(f"# utc={datetime.now(timezone.utc).isoformat()}")
    profile_id = profile.get("profile_id")
    if isinstance(profile_id, str) and profile_id.strip():
        lines.append(f"# profile_id={profile_id.strip()}")

    min_v = _tls_version(tls.get("tls_min_version"))
    max_v = _tls_version(tls.get("tls_max_version"))
    if min_v is not None:
        lines.append(f"tls_min={min_v}")
    if max_v is not None:
        lines.append(f"tls_max={max_v}")

    cipher_csv = _csv_int(tls.get("cipher_suites"))
    if cipher_csv is not None:
        lines.append(f"cipher_suites={cipher_csv}")

    cipher_mode = tls.get("cipher_mode")
    if isinstance(cipher_mode, str) and cipher_mode.strip():
        lines.append(f"cipher_mode={cipher_mode.strip()}")

    alpn_csv = _csv_tokens(tls.get("alpn_protocols"))
    if alpn_csv is not None:
        lines.append(f"alpn={alpn_csv}")

    ext_csv = _csv_int(tls.get("extensions"))
    if ext_csv is not None:
        lines.append(f"extension_order={ext_csv}")

    extension_mode = tls.get("extension_mode")
    if isinstance(extension_mode, str) and extension_mode.strip():
        lines.append(f"extension_mode={extension_mode.strip()}")

    sigalg_csv = _csv_int(tls.get("signature_algorithms"))
    if sigalg_csv is not None:
        lines.append(f"signature_algorithms={sigalg_csv}")

    supported_versions_csv = _csv_int(tls.get("supported_versions"))
    if supported_versions_csv is not None:
        lines.append(f"supported_versions={supported_versions_csv}")

    supported_groups_csv = _csv_int(tls.get("supported_groups"))
    if supported_groups_csv is not None:
        lines.append(f"supported_groups={supported_groups_csv}")

    key_share_groups_csv = _csv_int(tls.get("key_share_groups"))
    if key_share_groups_csv is not None:
        lines.append(f"key_share_groups={key_share_groups_csv}")

    psk_modes_csv = _csv_int(tls.get("psk_key_exchange_modes"))
    if psk_modes_csv is not None:
        lines.append(f"psk_key_exchange_modes={psk_modes_csv}")

    sni_mode = tls.get("sni_mode")
    if isinstance(sni_mode, str) and sni_mode.strip():
        lines.append(f"sni_mode={sni_mode.strip()}")

    grease = _bool_to_int_str(exec_ossl.get("enable_grease"))
    if grease is not None:
        lines.append(f"enable_grease={grease}")

    ch_perm = _bool_to_int_str(exec_ossl.get("enable_ch_xtn_permutation"))
    if ch_perm is not None:
        lines.append(f"enable_ch_xtn_permutation={ch_perm}")

    return "\n".join(lines) + "\n"


def emit_boringssl(profile: dict[str, Any]) -> str:
    tls = _nested(profile, "inputs", "tls_client_hello")
    if not isinstance(tls, dict):
        tls = {}

    exec_bssl = _nested(profile, "execution", "boringssl")
    if not isinstance(exec_bssl, dict):
        exec_bssl = {}

    lines: list[str] = []
    lines.append("# generated by scripts/fcs_emit.py")
    lines.append(f"# utc={datetime.now(timezone.utc).isoformat()}")
    profile_id = profile.get("profile_id")
    if isinstance(profile_id, str) and profile_id.strip():
        lines.append(f"# profile_id={profile_id.strip()}")

    min_v = _tls_version(tls.get("tls_min_version"))
    max_v = _tls_version(tls.get("tls_max_version"))
    if min_v is not None:
        lines.append(f"tls_min={min_v}")
    if max_v is not None:
        lines.append(f"tls_max={max_v}")

    cipher_csv = _csv_int(tls.get("cipher_suites"))
    if cipher_csv is not None:
        lines.append(f"cipher_suites={cipher_csv}")

    cipher_mode = tls.get("cipher_mode")
    if isinstance(cipher_mode, str) and cipher_mode.strip():
        lines.append(f"cipher_mode={cipher_mode.strip()}")

    alpn_csv = _csv_tokens(tls.get("alpn_protocols"))
    if alpn_csv is not None:
        lines.append(f"alpn={alpn_csv}")

    sigalg_csv = _csv_int(tls.get("signature_algorithms"))
    if sigalg_csv is not None:
        lines.append(f"signature_algorithms={sigalg_csv}")

    supported_versions_csv = _csv_int(tls.get("supported_versions"))
    if supported_versions_csv is not None:
        lines.append(f"supported_versions={supported_versions_csv}")

    supported_groups_csv = _csv_int(tls.get("supported_groups"))
    if supported_groups_csv is not None:
        lines.append(f"supported_groups={supported_groups_csv}")

    key_share_groups_csv = _csv_int(tls.get("key_share_groups"))
    if key_share_groups_csv is not None:
        lines.append(f"key_share_groups={key_share_groups_csv}")

    psk_modes_csv = _csv_int(tls.get("psk_key_exchange_modes"))
    if psk_modes_csv is not None:
        lines.append(f"psk_key_exchange_modes={psk_modes_csv}")

    ext_csv = _csv_int(tls.get("extensions"))
    if ext_csv is not None:
        lines.append(f"extension_order={ext_csv}")

    extension_mode = tls.get("extension_mode")
    if isinstance(extension_mode, str) and extension_mode.strip():
        lines.append(f"extension_mode={extension_mode.strip()}")

    sni_mode = tls.get("sni_mode")
    if isinstance(sni_mode, str) and sni_mode.strip():
        lines.append(f"sni_mode={sni_mode.strip()}")

    grease = _bool_to_int_str(exec_bssl.get("enable_grease"))
    if grease is not None:
        lines.append(f"enable_grease={grease}")

    ch_perm = _bool_to_int_str(exec_bssl.get("enable_ch_xtn_permutation"))
    if ch_perm is not None:
        lines.append(f"enable_ch_xtn_permutation={ch_perm}")

    return "\n".join(lines) + "\n"


EMITTERS = {
    "nss": emit_nss,
    "openssl": emit_openssl,
    "boringssl": emit_boringssl,
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Emit library-specific config from an FCS profile"
    )
    parser.add_argument("--input", required=True, help="Path to FCS profile (.yaml/.json)")
    parser.add_argument("--target", required=True, choices=sorted(EMITTERS.keys()))
    parser.add_argument("--output", required=True, help="Output file path")
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    input_path = pathlib.Path(args.input).expanduser().resolve()
    output_path = pathlib.Path(args.output).expanduser().resolve()

    profile = _load_profile(input_path)
    rendered = EMITTERS[args.target](profile)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(rendered, encoding="utf-8")
    print(f"wrote {args.target} config: {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
