#!/usr/bin/env bash
# JA4 config validation and generation.

validate_mode() {
  local mode="$1"
  case "$(lower "$mode")" in
    reorder|exact) return 0 ;;
    *)
      echo "[error] invalid mode: $mode" >&2
      echo "[hint] allowed: reorder, exact" >&2
      return 1
      ;;
  esac
}

validate_sni_mode() {
  local mode="$1"
  case "$(lower "$mode")" in
    present|domain|none|ip) return 0 ;;
    *)
      echo "[error] invalid --sni-mode: $mode" >&2
      echo "[hint] allowed: present, domain, none, ip" >&2
      return 1
      ;;
  esac
}

validate_ja4_params() {
  if [[ -n "$JA4_STRICT" ]] && ! is_valid_bool "$JA4_STRICT"; then
    echo "[error] invalid --strict: $JA4_STRICT" >&2
    exit 1
  fi

  if [[ -n "$JA4_SNI_MODE" ]] && ! validate_sni_mode "$JA4_SNI_MODE"; then
    exit 1
  fi

  if [[ -n "$JA4_CIPHER_MODE" ]] && ! validate_mode "$JA4_CIPHER_MODE"; then
    exit 1
  fi

  if [[ -n "$JA4_EXTENSION_MODE" ]] && ! validate_mode "$JA4_EXTENSION_MODE"; then
    exit 1
  fi

  if [[ -n "$JA4_ENABLE_GREASE" ]] && ! is_valid_bool "$JA4_ENABLE_GREASE"; then
    echo "[error] invalid --enable-grease: $JA4_ENABLE_GREASE" >&2
    exit 1
  fi

  if [[ -n "$JA4_ENABLE_CH_XTN_PERMUTATION" ]] && ! is_valid_bool "$JA4_ENABLE_CH_XTN_PERMUTATION"; then
    echo "[error] invalid --enable-ch-xtn-permutation: $JA4_ENABLE_CH_XTN_PERMUTATION" >&2
    exit 1
  fi

  for kv in "${JA4_EXTRA_KV[@]+"${JA4_EXTRA_KV[@]}"}"; do
    if [[ "$kv" != *=* ]]; then
      echo "[error] --set expects key=value, got: $kv" >&2
      exit 1
    fi
    if [[ -z "${kv%%=*}" ]]; then
      echo "[error] --set key cannot be empty: $kv" >&2
      exit 1
    fi
  done
}

write_ja4_config() {
  local config_out="$1"
  local config_in="$2"
  local script_name="$3"

  mkdir -p "$(dirname "$config_out")"
  if [[ -n "$config_in" ]]; then
    cp "$config_in" "$config_out"
  else
    cat > "$config_out" <<EOF
# Generated by $script_name
# Repo: $REPO_ROOT
EOF
  fi

  _append_kv() {
    local key="$1" value="$2"
    if [[ -n "$value" ]]; then
      printf '%s=%s\n' "$key" "$value" >> "$config_out"
    fi
  }

  _append_kv "tls_min" "$JA4_TLS_MIN"
  _append_kv "tls_max" "$JA4_TLS_MAX"
  _append_kv "strict" "$JA4_STRICT"
  _append_kv "cipher_suites" "$JA4_CIPHER_SUITES"
  _append_kv "cipher_mode" "$JA4_CIPHER_MODE"
  _append_kv "alpn" "$JA4_ALPN"
  _append_kv "signature_algorithms" "$JA4_SIGNATURE_ALGORITHMS"
  _append_kv "supported_versions" "$JA4_SUPPORTED_VERSIONS"
  _append_kv "supported_groups" "$JA4_SUPPORTED_GROUPS"
  _append_kv "key_share_groups" "$JA4_KEY_SHARE_GROUPS"
  _append_kv "psk_key_exchange_modes" "$JA4_PSK_KEY_EXCHANGE_MODES"
  _append_kv "extension_order" "$JA4_EXTENSION_ORDER"
  _append_kv "extension_mode" "$JA4_EXTENSION_MODE"
  _append_kv "sni_mode" "$JA4_SNI_MODE"
  _append_kv "enable_grease" "$JA4_ENABLE_GREASE"
  _append_kv "enable_ch_xtn_permutation" "$JA4_ENABLE_CH_XTN_PERMUTATION"

  for kv in "${JA4_EXTRA_KV[@]+"${JA4_EXTRA_KV[@]}"}"; do
    printf '%s\n' "$kv" >> "$config_out"
  done

  unset -f _append_kv
}

show_ja4_config() {
  local config_out="$1"
  local label="$2"
  echo "[info] effective $label config: $config_out"
  cat "$config_out"
}
