#!/usr/bin/env bash
set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/lib/env.sh"
source "$(dirname "${BASH_SOURCE[0]}")/lib/util.sh"

patch_dir="$REPO_ROOT/patches/nss"
pin_file="$REPO_ROOT/configs/firefox-build-pin.env"

workdir="${HOME}/build/firefox-ja4-stable"
repo_url="https://github.com/mozilla/gecko-dev.git"
branch="release"
ref=""
jobs=""
bootstrap=0
check_only=0
write_pin=0
ignore_pin=0
nss_only=0
python_bin=""
rust_toolchain=""
rustup_bin=""
rust_host_triple=""
rustc_bin=""
cargo_bin=""
recommended_rust_version=""

pin_firefox_ref=""
pin_firefox_branch=""
pin_nss_version=""
current_nss_version=""
resolved_ff_commit=""
resolved_ff_branch=""

usage() {
  cat <<'USAGE'
Usage: scripts/build_firefox_with_patched_nss.sh [options]

Builds Firefox (stable release channel) with local NSS patches from patches/nss.

Options:
  --workdir <path>         Build workspace (default: ~/build/firefox-ja4-stable)
  --repo-url <url>         Firefox source repo (default: gecko-dev mirror)
  --branch <name>          Firefox branch (default: release)
  --ref <git-ref>          Optional exact commit/tag/branch to checkout
  --pin-file <path>        Pin config file (default: configs/firefox-build-pin.env)
  --check-only             Only verify patch applicability, no build
  --write-pin              Write FIREFOX_BRANCH/FIREFOX_REF/NSS_VERSION to pin file
  --ignore-pin             Ignore NSS_VERSION mismatch from pin file
  --nss-only               Build only the NSS subtree inside Gecko
  --jobs <n>               Build parallelism (default: auto-detect)
  --python <path>          Python interpreter for ./mach (e.g. /opt/homebrew/bin/python3.10)
  --rust-toolchain <name>  rustup toolchain/version to use for mach build (e.g. 1.86.0)
  --bootstrap              Run ./mach bootstrap before build
  -h, --help               Show this help
USAGE
}

load_pin_file() {
  local file="$1"
  local line
  local key
  local value

  if [[ ! -f "$file" ]]; then
    return 0
  fi

  while IFS= read -r line; do
    [[ -z "$line" ]] && continue
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ "$line" != *=* ]] && continue

    key="${line%%=*}"
    value="${line#*=}"
    key="${key//[[:space:]]/}"
    value="$(printf '%s' "$value" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
    value="${value%\"}"
    value="${value#\"}"

    case "$key" in
      FIREFOX_REF)
        pin_firefox_ref="$value"
        ;;
      FIREFOX_BRANCH)
        pin_firefox_branch="$value"
        ;;
      NSS_VERSION)
        pin_nss_version="$value"
        ;;
    esac
  done < "$file"
}

detect_nss_version() {
  local src="$1"
  local version=""

  if [[ -f "$src/security/nss/coreconf/version.mk" ]]; then
    version="$(awk -F= '/^NSS_VERSION[[:space:]]*=/{gsub(/[[:space:]]/,"",$2);print $2; exit}' \
      "$src/security/nss/coreconf/version.mk")"
  fi

  if [[ -z "$version" && -f "$src/security/nss/lib/nss/nss.h" ]]; then
    version="$(awk -F'"' '/#define[[:space:]]+NSS_VERSION[[:space:]]+"/{print $2; exit}' \
      "$src/security/nss/lib/nss/nss.h")"
  fi

  printf '%s' "$version"
}

write_pin_file() {
  local file="$1"
  local ff_branch="$2"
  local ff_commit="$3"
  local nss_ver="$4"

  mkdir -p "$(dirname "$file")"
  cat > "$file" <<PIN
# Generated by scripts/build_firefox_with_patched_nss.sh
# Branch for Firefox stable channel in gecko-dev mirror.
FIREFOX_BRANCH=$ff_branch
# Exact tested commit on that branch.
FIREFOX_REF=$ff_commit
# Expected NSS version inside Firefox source tree.
NSS_VERSION=$nss_ver
PIN
}

run_mach() {
  local src="$1"
  shift

  local -a env_cmd=()
  if [[ -n "$rustc_bin" ]]; then
    env_cmd+=("RUSTC=$rustc_bin")
  fi
  if [[ -n "$cargo_bin" ]]; then
    env_cmd+=("CARGO=$cargo_bin")
  fi
  if [[ -n "$rust_toolchain" ]]; then
    env_cmd+=("RUSTUP_TOOLCHAIN=$rust_toolchain")
  fi

  if [[ -n "$python_bin" ]]; then
    (cd "$src" && env "${env_cmd[@]}" MOZCONFIG="$mozconfig_path" "$python_bin" ./mach "$@")
  else
    (cd "$src" && env "${env_cmd[@]}" MOZCONFIG="$mozconfig_path" ./mach "$@")
  fi
}

detect_recommended_rust_version() {
  local src="$1"
  local version=""
  local rust_yml="$src/taskcluster/kinds/toolchain/rust.yml"
  local cargo_toml="$src/Cargo.toml"

  if [[ -f "$rust_yml" ]]; then
    version="$(awk '
      $0 ~ /^linux64-rust-macos-[0-9.]+:/ { in_block=1; next }
      in_block && $0 ~ /^linux64-rust-[^:]+:/ { in_block=0 }
      in_block && $0 ~ /--channel/ {
        n = split($0, parts, "'\''")
        if (n >= 4) {
          print parts[4]
          exit
        }
        if (n >= 2) {
          print parts[2]
          exit
        }
        exit
      }
    ' "$rust_yml")"
  fi

  if [[ -z "$version" && -f "$cargo_toml" ]]; then
    version="$(awk -F'"' '/^rust-version[[:space:]]*=/{print $2; exit}' "$cargo_toml")"
  fi

  printf '%s' "$version"
}

setup_rust_toolchain() {
  local src="$1"
  local requested="$2"
  local toolchain_path=""

  recommended_rust_version="$(detect_recommended_rust_version "$src")"

  if [[ -z "$requested" ]]; then
    requested="$recommended_rust_version"
  fi

  if [[ -z "$requested" ]]; then
    return 0
  fi

  rustup_bin="$(command -v rustup || true)"
  if [[ -z "$rustup_bin" ]]; then
    echo "[error] rustup not found, but an explicit Firefox Rust toolchain is required." >&2
    echo "[hint] install rustup from https://rustup.rs/ and then install Rust $requested" >&2
    exit 1
  fi

  rust_host_triple="$(rustc -vV 2>/dev/null | sed -n 's/^host: //p')"
  if [[ -z "$rust_host_triple" ]]; then
    rust_host_triple="$(uname -m)-apple-darwin"
  fi

  rust_toolchain="$requested"
  toolchain_path="$HOME/.rustup/toolchains/${requested}-${rust_host_triple}"
  if [[ ! -x "$toolchain_path/bin/rustc" || ! -x "$toolchain_path/bin/cargo" ]]; then
    toolchain_path="$HOME/.rustup/toolchains/${requested}"
  fi

  if [[ ! -x "$toolchain_path/bin/rustc" || ! -x "$toolchain_path/bin/cargo" ]]; then
    echo "[error] required Rust toolchain '$requested' is not installed." >&2
    echo "[hint] install it with: rustup toolchain install $requested" >&2
    if [[ -n "$recommended_rust_version" ]]; then
      echo "[hint] this Gecko stand expects the $recommended_rust_version toolchain family, not your global stable." >&2
    fi
    exit 1
  fi

  rustc_bin="$toolchain_path/bin/rustc"
  cargo_bin="$toolchain_path/bin/cargo"
  echo "[info] using Rust toolchain: $requested ($("$rustc_bin" --version 2>&1))"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --workdir)
      workdir="$2"
      shift 2
      ;;
    --repo-url)
      repo_url="$2"
      shift 2
      ;;
    --branch)
      branch="$2"
      shift 2
      ;;
    --ref)
      ref="$2"
      shift 2
      ;;
    --pin-file)
      pin_file="$2"
      shift 2
      ;;
    --check-only)
      check_only=1
      shift
      ;;
    --write-pin)
      write_pin=1
      shift
      ;;
    --ignore-pin)
      ignore_pin=1
      shift
      ;;
    --nss-only)
      nss_only=1
      shift
      ;;
    --jobs)
      jobs="$2"
      shift 2
      ;;
    --python)
      python_bin="$2"
      shift 2
      ;;
    --rust-toolchain)
      rust_toolchain="$2"
      shift 2
      ;;
    --bootstrap)
      bootstrap=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "[error] unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

load_pin_file "$pin_file"
if [[ -z "$ref" && -n "$pin_firefox_ref" ]]; then
  ref="$pin_firefox_ref"
fi
if [[ -n "$pin_firefox_branch" ]]; then
  branch="$pin_firefox_branch"
fi

if [[ ! -d "$patch_dir" ]] || ! ls "$patch_dir"/*.patch >/dev/null 2>&1; then
  echo "[error] no NSS patches found in $patch_dir" >&2
  exit 1
fi

if [[ -z "$jobs" ]]; then
  jobs="$(detect_jobs)"
fi

# Auto-detect a compatible Python (<= 3.12) for mach.
if [[ -z "$python_bin" ]]; then
  for _pyver in python3.12 python3.11 python3.10; do
    for _pydir in "/opt/homebrew/bin" "/usr/local/bin" "/usr/bin"; do
      if [[ -x "$_pydir/$_pyver" ]]; then
        python_bin="$_pydir/$_pyver"
        break 2
      fi
    done
  done
  if [[ -z "$python_bin" ]]; then
    echo "[error] Python <= 3.12 not found. mach requires Python 3.10-3.12." >&2
    echo "[hint]  brew install python@3.12" >&2
    exit 1
  fi
  echo "[info] using Python: $python_bin ($("$python_bin" --version 2>&1))"
fi

mkdir -p "$workdir"
src_dir="$workdir/gecko-dev"
mozconfig_path="$workdir/mozconfig-ja4-stable"

if [[ ! -d "$src_dir/.git" ]]; then
  echo "[info] cloning Firefox source ($branch) into $src_dir"
  retry 3 5 git clone --branch "$branch" --single-branch --depth 1 "$repo_url" "$src_dir"
  # Mark this checkout as managed by ja4-spoofer so destructive cleanups
  # below are gated to it and won't touch a developer's own gecko-dev.
  touch "$src_dir/.ja4-managed-checkout"
else
  echo "[info] reusing existing source in $src_dir"
  cleanup_git_locks "$src_dir"
  retry 3 5 git -C "$src_dir" fetch --prune --depth 1 origin "$branch"
fi

  # Clean stale untracked files from previous checkouts (e.g. different branches
  # may leave behind files that break the build system). Gated to ja4-managed
  # checkouts so a stray `--workdir` pointing at someone's own gecko-dev tree
  # cannot wipe their work.
  if [[ -f "$src_dir/.ja4-managed-checkout" ]]; then
    echo "[info] cleaning untracked files from source tree"
    git -C "$src_dir" clean -fd -q 2>/dev/null || true
  else
    echo "[warn] $src_dir is not a ja4-managed checkout (no .ja4-managed-checkout marker)"
    echo "[warn] skipping 'git clean -fd' to preserve any local work"
  fi

if [[ -n "$ref" ]]; then
  echo "[info] checking out pinned ref $ref"
  cleanup_git_locks "$src_dir"
  if ! git -C "$src_dir" checkout -f "$ref" 2>/dev/null; then
    echo "[info] fetching pinned ref $ref"
    retry 3 5 git -C "$src_dir" fetch --depth 1 origin "$ref"
    git -C "$src_dir" checkout -f FETCH_HEAD
  fi
  resolved_ff_branch="$(git -C "$src_dir" branch --show-current || true)"
else
  echo "[info] checking out stable branch $branch"
  git -C "$src_dir" checkout -f "$branch"
  if git -C "$src_dir" diff --quiet && git -C "$src_dir" diff --cached --quiet; then
    git -C "$src_dir" pull --ff-only origin "$branch"
  else
    echo "[warn] source tree has local changes; skipping fast-forward pull"
  fi
  resolved_ff_branch="$branch"
fi

resolved_ff_commit="$(git -C "$src_dir" rev-parse HEAD)"
current_nss_version="$(detect_nss_version "$src_dir")"
setup_rust_toolchain "$src_dir" "$rust_toolchain"
if [[ -n "$current_nss_version" ]]; then
  echo "[info] detected NSS version: $current_nss_version"
else
  echo "[warn] could not detect NSS version from source tree"
fi

if [[ "$ignore_pin" -eq 0 && -n "$pin_nss_version" && -n "$current_nss_version" && "$pin_nss_version" != "$current_nss_version" ]]; then
  echo "[error] pinned NSS_VERSION=$pin_nss_version, but source contains NSS_VERSION=$current_nss_version" >&2
  echo "[hint] update $pin_file, pass --ignore-pin, or use --write-pin after validation" >&2
  exit 1
fi

if ! git -C "$src_dir" diff --quiet -- security/nss || ! git -C "$src_dir" diff --cached --quiet -- security/nss; then
  echo "[info] resetting local changes under security/nss before patch apply"
  git -C "$src_dir" checkout -- security/nss
fi

echo "[info] applying NSS patches into security/nss"
for patch in "$patch_dir"/*.patch; do
  if git -C "$src_dir" apply --reverse --check --directory=security/nss "$patch" >/dev/null 2>&1; then
    echo "[skip] already applied: $(basename "$patch")"
    continue
  fi
  git -C "$src_dir" apply --check --directory=security/nss "$patch"
  if [[ "$check_only" -eq 1 ]]; then
    echo "[ok] applicable: $(basename "$patch")"
  else
    git -C "$src_dir" apply --directory=security/nss "$patch"
    echo "[ok] applied: $(basename "$patch")"
  fi
done

if [[ "$check_only" -eq 1 ]]; then
  if [[ "$write_pin" -eq 1 ]]; then
    write_pin_file "$pin_file" "${resolved_ff_branch:-$branch}" "$resolved_ff_commit" "${current_nss_version:-unknown}"
    echo "[ok] wrote pin file: $pin_file"
  fi
  cat <<EOF2
[ok] patch compatibility check finished
firefox_branch: ${resolved_ff_branch:-$branch}
firefox_commit: $resolved_ff_commit
nss_version: ${current_nss_version:-unknown}
EOF2
  exit 0
fi

# Auto-bootstrap on first build: install Mozilla clang toolchain (with lld linker).
# Must happen BEFORE mozconfig generation so clang paths are detected.
if [[ "$bootstrap" -eq 1 ]] || [[ ! -x "$HOME/.mozbuild/clang/bin/clang" ]]; then
  echo "[info] running mach bootstrap (installing Mozilla build toolchain)..."
  echo "[info] this is needed once and may take a while."
  # Bootstrap needs a minimal mozconfig to know we're building the browser.
  cat > "$mozconfig_path" <<'EOF2'
mk_add_options MOZ_OBJDIR=@TOPSRCDIR@/obj-ja4-stable
ac_add_options --enable-application=browser
EOF2
  # Pipe 'yes' to auto-accept any interactive prompts.
  yes '' 2>/dev/null | run_mach "$src_dir" bootstrap --application-choice browser || true
fi

# Generate full mozconfig (after bootstrap so clang paths are available).
cat > "$mozconfig_path" <<'EOF2'
mk_add_options MOZ_OBJDIR=@TOPSRCDIR@/obj-ja4-stable
ac_add_options --enable-application=browser
ac_add_options --disable-tests
ac_add_options --disable-updater
EOF2

if [[ "$(uname -s)" == "Darwin" ]]; then
  {
    echo 'ac_add_options --disable-bootstrap'
    echo 'ac_add_options --without-wasm-sandboxed-libraries'
    # Prefer the SDK bundled by `mach bootstrap` — it is version-matched to
    # the bundled clang/bindgen and avoids libc++ template-alias breakage
    # when the system Xcode is newer than what bindgen understands. Falls
    # back to xcrun (works for any user with CommandLineTools) so the
    # script is portable across machines without hardcoded user paths.
    macos_sdk=""
    bundled_sdk="$(find "$HOME/.mozbuild" -maxdepth 1 -type d -name 'MacOSX*.sdk' 2>/dev/null | sort -V | tail -1)"
    if [[ -n "$bundled_sdk" && -d "$bundled_sdk" ]]; then
      macos_sdk="$bundled_sdk"
    elif command -v xcrun >/dev/null 2>&1; then
      macos_sdk="$(xcrun --show-sdk-path 2>/dev/null || true)"
    fi
    if [[ -n "$macos_sdk" && -d "$macos_sdk" ]]; then
      echo "ac_add_options --with-macos-sdk=$macos_sdk"
    fi
    if [[ -x "$HOME/.mozbuild/clang/bin/clang" && -x "$HOME/.mozbuild/clang/bin/clang++" ]]; then
      # Mozilla clang toolchain (installed by mach bootstrap)
      echo 'ac_add_options --enable-linker=lld'
      echo "export CC=$HOME/.mozbuild/clang/bin/clang"
      echo "export CXX=$HOME/.mozbuild/clang/bin/clang++"
    elif [[ -x "/opt/homebrew/opt/llvm/bin/clang" ]]; then
      # Homebrew LLVM as fallback (brew install llvm)
      echo 'ac_add_options --enable-linker=lld'
      echo "export CC=/opt/homebrew/opt/llvm/bin/clang"
      echo "export CXX=/opt/homebrew/opt/llvm/bin/clang++"
      echo "export AR=/opt/homebrew/opt/llvm/bin/llvm-ar"
      echo "export NM=/opt/homebrew/opt/llvm/bin/llvm-nm"
      echo "export RANLIB=/opt/homebrew/opt/llvm/bin/llvm-ranlib"
    fi
  } >> "$mozconfig_path"
fi

if [[ "$nss_only" -eq 1 ]]; then
  echo "[info] building patched NSS inside Gecko (jobs=$jobs)"
  run_mach "$src_dir" build -j "$jobs" security/nss
else
  echo "[info] building Firefox stable (jobs=$jobs)"
  run_mach "$src_dir" build -j "$jobs"
fi

if [[ "$nss_only" -eq 1 ]]; then
  cat <<EOF2
[ok] NSS-only build finished
source: $src_dir
branch: ${resolved_ff_branch:-$branch}
commit: $resolved_ff_commit
target: security/nss

Rust toolchain used:
  ${rust_toolchain:-system default}
EOF2
  exit 0
fi

binary_path=""
if [[ -x "$src_dir/obj-ja4-stable/dist/Firefox.app/Contents/MacOS/firefox" ]]; then
  binary_path="$src_dir/obj-ja4-stable/dist/Firefox.app/Contents/MacOS/firefox"
elif [[ -x "$src_dir/obj-ja4-stable/dist/Nightly.app/Contents/MacOS/firefox" ]]; then
  binary_path="$src_dir/obj-ja4-stable/dist/Nightly.app/Contents/MacOS/firefox"
elif [[ -x "$src_dir/obj-ja4-stable/dist/bin/firefox" ]]; then
  binary_path="$src_dir/obj-ja4-stable/dist/bin/firefox"
else
  binary_path="$src_dir/obj-ja4-stable/dist"
fi

if [[ "$write_pin" -eq 1 ]]; then
  write_pin_file "$pin_file" "${resolved_ff_branch:-$branch}" "$resolved_ff_commit" "${current_nss_version:-unknown}"
  echo "[ok] wrote pin file: $pin_file"
fi

cat <<EOF2
[ok] stable build finished
source: $src_dir
branch: ${resolved_ff_branch:-$branch}
commit: $resolved_ff_commit
binary: $binary_path

Example run with NSS JA4 config:
  NSS_JA4_CONFIG=/path/to/nss.conf NSS_JA4_DUMP=/tmp/nss-dump.conf "$binary_path"

Rust toolchain used:
  ${rust_toolchain:-system default}
EOF2
